### ISSUE TITLE
Set serviceType to null (hex 0x00)

### ISSUE THREAD

**Issue by Nestik** [wso2-extensions/esb-connector-smpp#16]
**Description:**
Hi, please rewrite this code
```
public void setServiceType(String serviceType) {
        if (StringUtils.isEmpty(serviceType)) {
            serviceType = SMPPConstants.CMT;
        }
        this.serviceType = serviceType;
}
```
in SMSDTO.java file.

If ServiceType null, this connector addet "CMT" string to ServiceType, but according to SMPP specification  need hex 0x00 (default). My SMSC acceptance only hex 0x00 in ServiceType. Therefore, I can not be used this connector.

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3526
