### ISSUE TITLE
Cannot set default value for messageClass for Data Encoding

### ISSUE THREAD

**Issue by jagathsisira** [wso2-extensions/esb-connector-smpp#17]
I wanted to set null for messageClass in JSMPP submitShortMessage method but this connector set CLASS1 as the default value if I kept the Synapse Configuration empty. 

The JSMPP submitShortMessage method's Data Encoding parameters I expected to set:
`new GeneralDataCoding(Alphabet.ALPHA_DEFAULT, null, false)`

The synapse configuration I tried to achieve this:
`<messageClass></messageClass>`

Default value is set as CLASS1 here. It should be null, if no value is provided from synapse config.
[https://github.com/wso2-extensions/esb-connector-smpp/blob/master/src/main/java/org/wso2/carbon/esb/connector/SMSDTO.java#L140](https://github.com/wso2-extensions/esb-connector-smpp/blob/master/src/main/java/org/wso2/carbon/esb/connector/SMSDTO.java#L140)

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3525
